### ISSUE TITLE
fish: Unknown command '__budspencer_preexec'

### ISSUE THREAD

**Issue by Ramblurr** [oh-my-fish/theme-budspencer#42] opened 2016-10-31 11:44 UTC
enabling budspencer, then opening a new fish session results in this error and a hang when executing any command: 

```
fish: Unknown command '__budspencer_preexec'
```

I have added the following line to the beginning of my `$OMF_CONFIG/init.fish`

```
 set -U fish_key_bindings fish_vi_key_bindings
```

Any idea what's up?

**Comment by stephane-r** [comment] 2018-09-14 18:10
Same problem .. no solution ?

**Comment by fourcolors** [comment] 2019-05-21 23:33
I have the same problem here. I was using `fisher` to install the theme however. Could that make the difference?

**Comment by AdwinKing** [comment] 2019-06-05 14:21
Duplicate of # 47

**Comment by clayauld** [comment] 2019-10-08 17:27
Issue should be resolved after new updates.

**Closed by clayauld** 2019-10-08 17:27 UTC

**Comment by mmsaeed509** [comment] 2021-12-21 15:24
## I didn't find a solution to this issue

![Screenshot_17](https://user-images.githubusercontent.com/62524855/146954932-0afbb836-5467-48d4-aacd-41291c7825e4.png)
