### ISSUE TITLE
budspencer don't show folder path on the right

### ISSUE THREAD

**Issue by stephane-r** [oh-my-fish/theme-budspencer#54] opened 2018-09-14 07:48 UTC
Hi community !

I've install this very nice fish theme on my Linux, but the folder path on the right is not show. I've the command delay and the git branch on the left only.

I've see the README and i don't found information about this.

Anyone have an idea ?

Thank you !

**Comment by kuvaldini** [comment] 2019-03-01 14:06
The same error on ubuntu fish v2.7

**Comment by AdwinKing** [comment] 2019-06-05 14:17
You may have a look at /home/$USERNAME/.config/fish/functions/.
In my case I need to create soft links to files in /home/$USERNAME/.local/share/omf/themes/budspencer/

**Comment by AdwinKing** [comment] 2019-06-05 14:22
Duplicate of #47

**Comment by clayauld** [comment] 2019-10-08 17:28
Issue should be resolved with new updates

**Closed by clayauld** 2019-10-08 17:28 UTC
